### ISSUE TITLE
CRUD Cliente Backend

### ISSUE THREAD

**Issue by worker-8** [aether7/azap#22]
# TODO
Create all operations CRUD for Backend,

- Create
- List and search
- Update
- Delete (In this case only logical)

*note* Only between Frontend/Backend with out DataBase

**Comment by worker-8** [comment]
Observations
- Method get list
- Method get filter/{id_filter}
- Method get showCreateCliente
- Method post createUser
- Method get showUpdateCliente/{id}
- Method post updateCliente
- Method get deleteCliente/{id}
reguards
@Draaakos

**Comment by aether7** [comment]
https://github.com/aether7/azap/issues/28
